# where do you want to generate the config files
target_dir = "./dist"
# name of your configuration
name = "horn"
dotidx_root = "/dotidx"
dotidx_backup = "/dotidx/backup"
dotidx_run = "/dotidx/run"
dotidx_logs = "/dotidx/logs"

[dotidx_db]
type = "postgres"
version = 16
name = "dotidx"
ip = "192.168.1.36"
user = "dotidx"
password = "funradio"
port = 5434
memory = "64GB"
data_dir = "/polkadot/postgres_data/dotidx"
run_dir = "/polkadot/postgres_data/run"
whitelisted_ip = ["192.168.1.102", "192.168.1.36", "192.168.1.37"]

[dotidx_batch]
start_range = 1
end_range = -1
batch_size = 10
max_workers = 4
batching = "batch"
flush_timeout = "15s"

[dotidx_fe]
ip = "127.0.0.1"
port = 8080
static_path = "./app"

[parachains.polkadot.polkadot]
name = "polkadot"  # name for the polkadot binary --chain parameter
port = 9944
basepath = "/polkadot/polkadot-relay-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 10800
sidecar_ip = "127.0.0.1"
sidecar_port = 10800  # will use +1 +2 etc for each sidecar instance
sidecar_count = 5

[parachains.polkadot.assethub]
name = "asset-hub-polkadot"  # name for the polkadot binary --chain parameter
port = 9946
basepath = "/polkadot/polkadot-assethub-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 10900
sidecar_ip = "127.0.0.1"
sidecar_port = 10900  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2

[parachains.polkadot.people]
name = "people-polkadot"  # name for the polkadot binary --chain parameter
port = 9948
basepath = "/polkadot/people-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11000
sidecar_ip = "127.0.0.1"
sidecar_port = 11000  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2

[parachains.polkadot.collectives]
name = "collectives-polkadot"  # name for the polkadot binary --chain parameter
port = 9950
basepath = "/polkadot/polkadot-collectives-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11100
sidecar_ip = "127.0.0.1"
sidecar_port = 11100  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2

[parachains.polkadot.mythos]
name = "mythos"
port = 9952
basepath = "/dotidx/polkadot-mythos-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11200
sidecar_ip = "127.0.0.1"
sidecar_port = 11200  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2

[parachains.polkadot.frequency]
name = "frequency"
port = 9954
basepath = "/dotidx/polkadot-frequency-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11300
sidecar_ip = "127.0.0.1"
sidecar_port = 11300  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2

[parachains.kusama.kusama]
name = "kusama"  # name for the polkadot binary --chain parameter
port = 19944
basepath = "/polkadot/kusama-relay-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 20800
sidecar_ip = "127.0.0.1"
sidecar_port = 20800  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2

[parachains.kusama.assethub]
name = "kusama-assethub"  # name for the polkadot binary --chain parameter
port = 19944
basepath = "/polkadot/kusama-assethub-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 20900
sidecar_ip = "127.0.0.1"
sidecar_port = 20900  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2

[parachains.kusama.accurast]
name = "kusama-accurast"  # name for the polkadot binary --chain parameter
port = 19944
basepath = "/polkadot/kusama-accurast-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 21000
sidecar_ip = "127.0.0.1"
sidecar_port = 21000  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2

[filesystem]
zfs = true

[monitoring]
user = "prometheus"
