# where do you want to generate the config files
target_dir = "/dotidx/etc"
# name of your configuration
name = "horn"
dotidx_root = "/dotidx"
dotidx_backup = "/dotidx/backup"
dotidx_run = "/dotidx/run"
dotidx_runtime = "/dotidx/runtim"
dotidx_logs = "/dotidx/logs"
dotidx_bin = "/dotidx/bin"

[dotidx_db]
type = "postgres"
version = 16
name = "dotidx"
ip = "192.168.1.36"
user = "dotidx"
password = "funradio"
port = 5434
memory = "64GB"
data_dir = "/polkadot/postgres_data/dotidx"
run_dir = "/polkadot/postgres_data/run"
whitelisted_ip = ["192.168.1.102", "192.168.1.36", "192.168.1.37"]

[dotidx_batch]
start_range = 1
end_range = -1
batch_size = 10
max_workers = 4
batching = "batch"
flush_timeout = "15s"

[dotidx_fe]
ip = "127.0.0.1"
port = 8080
static_path = "./app"

[parachains.polkadot.polkadot]
name = "polkadot"  # name for the polkadot binary --chain parameter
relay_ip = "192.168.1.36"
port_ws = 9943
port_rpc = 9944
basepath = "/polkadot/polkadot-relay-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 10800
sidecar_ip = "127.0.0.1"
sidecar_port = 10800  # will use +1 +2 etc for each sidecar instance
sidecar_count = 5
prometheus_port = 9615

[parachains.polkadot.assethub]
name = "asset-hub-polkadot"  # name for the polkadot binary --chain parameter
node_ip = "192.168.1.36"
port_ws = 9945
port_rpc = 9946
basepath = "/dotidx/polkadot-assethub-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 10900
sidecar_ip = "127.0.0.1"
sidecar_port = 10900  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 9616

[parachains.polkadot.people]
name = "people-polkadot"  # name for the polkadot binary --chain parameter
node_ip = "192.168.1.36"
port_ws = 9947
port_rpc = 9948
basepath = "/dotidx/polkadot-people-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11000
sidecar_ip = "127.0.0.1"
sidecar_port = 11000  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 9617

[parachains.polkadot.collectives]
name = "collectives-polkadot"  # name for the polkadot binary --chain parameter
node_ip = "192.168.1.36"
port_ws = 9949
port_rpc = 9950
basepath = "/dotidx/polkadot-collectives-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11100
sidecar_ip = "127.0.0.1"
sidecar_port = 11100  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 9618

[parachains.polkadot.mythos]
name = "mythos"
node_ip = "192.168.1.36"
port_ws = 9951
port_rpc = 9952
basepath = "/dotidx/polkadot-mythos-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11200
sidecar_ip = "127.0.0.1"
sidecar_port = 11200  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 9619

[parachains.polkadot.frequency]
name = "frequency"
node_ip = "192.168.1.36"
port_ws = 9953
port_rpc = 9954
basepath = "/dotidx/polkadot-frequency-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11300
sidecar_ip = "127.0.0.1"
sidecar_port = 11300  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 9620

[parachains.kusama.kusama]
name = "polkadot"  # name for the polkadot binary --chain parameter
relay_ip = "192.168.1.36"
port_ws = 19943
port_rpc = 19944
basepath = "/dotix/kusama-relay-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 20800
sidecar_ip = "127.0.0.1"
sidecar_port = 20800  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 19615

[parachains.kusama.assethub]
name = "kusama-assethub"  # name for the polkadot binary --chain parameter
node_ip = "192.168.1.36"
port_ws = 19945
port_rpc = 19946
basepath = "/dotidx/kusama-assethub-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 20900
sidecar_ip = "127.0.0.1"
sidecar_port = 20900  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 19616

[parachains.kusama.accurast]
name = "kusama-accurast"  # name for the polkadot binary --chain parameter
node_ip = "192.168.1.36"
port_ws = 19947
port_rpc = 19948
basepath = "/dotidx/kusama-accurast-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 21000
sidecar_ip = "127.0.0.1"
sidecar_port = 21000  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 19616

[filesystem]
zfs = true

[monitoring]
user = "prometheus"
