## ------------------------------------------------------ -*- toml -*- --
## This file generates all the other configuration files.
## Usage:
##     dixmgr -conf this.file.toml
## ----------------------------------------------------------------------
## Example of config with multiple machines
## 192.168.1.36 run the polkadot nodes
## 192.168.1.37 run the kusama nodes
## 192.168.1.32 run the admin / monitoring stuff
## 192.168.1.36 run the frontend / live indexer / batch indexer / cron
##
## to give an idea of how many nodes you need to run:
## 36: amd threadripper 64 cores 256GB RAM 6x10TB SATA + 4x2TB SSD
## 37: amd mini-pc       6 cores  16GB RAM 2x10TB SATA
## 32: intel i9900k      8 cores  32GB RAM 2x20TB SATA
## everything could run easily on the threadripper
## ----------------------------------------------------------------------


# where do you want to generate the config files
target_dir = "/dotidx/etc"

# name of your configuration
name = "horn"
dotidx_root = "/dotidx"
dotidx_backup = "/dotidx/backup"
dotidx_run = "/dotidx/run"
dotidx_runtime = "/dotidx/runtim"
dotidx_logs = "/dotidx/logs"
dotidx_bin = "/dotidx/bin"
dotidx_static = "/dotidx/static"

[dotidx_db]
type = "postgres"
version = 16
name = "dotidx"
ip = "192.168.1.36"
user = "dotidx"
password = "funradio"
port = 5434
memory = "64GB"
data_dir = "/db/postgres_data/dotidx"
run_dir = "/db/postgres_data/run"
whitelisted_ip = ["192.168.1.102", "192.168.1.36", "192.168.1.36", "192.168.1.32"]

[dotidx_batch]
start_range = 1
end_range = -1
batch_size = 10
max_workers = 8
batching = "batch"
flush_timeout = "15s"

[dotidx_fe]
ip = "192.168.1.36"
port = 8080
static_path = "/dotidx/static"

[parachains.polkadot.polkadot]
name = "polkadot"  # name for the polkadot binary --chain parameter
bin = "/dotidx/bin/polkadot"
relay_ip = "192.168.1.36"
port_ws = 9943
port_rpc = 9944
basepath = "/dotidx/polkadot-relay-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 10800
sidecar_ip = "192.168.1.36"
sidecar_port = 10800  # will use +1 +2 etc for each sidecar instance
sidecar_count = 5
prometheus_port = 9615
sidecar_prometheus_port = 10850

[parachains.polkadot.assethub]
name = "asset-hub-polkadot"  # name for the polkadot binary --chain parameter
bin = "/dotidx/bin/polkadot-parachain"
node_ip = "192.168.1.36"
port_ws = 9945
port_rpc = 9946
basepath = "/dotidx/polkadot-assethub-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 10900
sidecar_ip = "192.168.1.36"
sidecar_port = 10900  # will use +1 +2 etc for each sidecar instance
sidecar_count = 5
prometheus_port = 9616
sidecar_prometheus_port = 10950

[parachains.polkadot.people]
name = "people-polkadot"  # name for the polkadot binary --chain parameter
bin = "/dotidx/bin/polkadot-parachain"
node_ip = "192.168.1.36"
port_ws = 9947
port_rpc = 9948
basepath = "/dotidx/polkadot-people-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11000
sidecar_ip = "192.168.1.36"
sidecar_port = 11000  # will use +1 +2 etc for each sidecar instance
sidecar_count = 2
prometheus_port = 9617
sidecar_prometheus_port = 11050

[parachains.polkadot.collectives]
name = "collectives-polkadot"  # name for the polkadot binary --chain parameter
bin = "/dotidx/bin/polkadot-parachain"
node_ip = "192.168.1.36"
port_ws = 9949
port_rpc = 9950
basepath = "/dotidx/polkadot-collectives-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11100
sidecar_ip = "192.168.1.36"
sidecar_port = 11100  # will use +1 +2 etc for each sidecar instance
sidecar_prometheus_port = 11150
sidecar_count = 2
prometheus_port = 9618

[parachains.polkadot.mythos]
name = "mythos"
bin = "/dotidx/bin/mythos-node"
node_ip = "192.168.1.36"
port_ws = 9951
port_rpc = 9952
basepath = "/dotidx/polkadot-mythos-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11200
sidecar_ip = "192.168.1.36"
sidecar_port = 11200  # will use +1 +2 etc for each sidecar instance
sidecar_prometheus_port = 11250
sidecar_count = 5
prometheus_port = 9619

[parachains.polkadot.frequency]
name = "frequency"
bin = "/dotidx/bin/frequency-v1.15.2"
node_ip = "192.168.1.36"
port_ws = 9953
port_rpc = 9954
basepath = "/dotidx/polkadot-frequency-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 11300
sidecar_ip = "192.168.1.36"
sidecar_port = 11300  # will use +1 +2 etc for each sidecar instance
sidecar_count = 5
sidecar_prometheus_port = 11350
prometheus_port = 9620

[parachains.kusama.kusama]
name = "kusama"  # name for the polkadot binary --chain parameter
bin = "/dotidx/bin/polkadot"
relay_ip = "192.168.1.36"
port_ws = 19943
port_rpc = 19944
basepath = "/dotidx/kusama-relay-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 20800
sidecar_ip = "192.168.1.36"
sidecar_port = 20800  # will use +1 +2 etc for each sidecar instance
sidecar_count = 5
prometheus_port = 19615
sidecar_prometheus_port = 20850

[parachains.kusama.assethub]
name = "asset-hub-kusama"  # name for the polkadot binary --chain parameter
bin = "/dotidx/bin/polkadot-parachain"
node_ip = "192.168.1.36"
port_ws = 19945
port_rpc = 19946
basepath = "/dotidx/kusama-assethub-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 20900
sidecar_ip = "192.168.1.36"
sidecar_port = 20900  # will use +1 +2 etc for each sidecar instance
sidecar_count = 5
prometheus_port = 19616
sidecar_prometheus_port = 20950

[parachains.kusama.acurast]
name = "/dotidx/runtime/acurast/acurast-kusama-parachain-2239-raw.json"  # name for the polkadot binary --chain parameter
bin = "/dotidx/bin/acurast-node"
bootnodes = "--bootnodes /ip4/82.220.38.222/tcp/30334/ws/p2p/12D3KooWKrSDeVQ4tVQ1eGjqVAhAW3cgMQFHNCBbJrpmupEvdD4A"
node_ip = "192.168.1.36"
port_ws = 19947
port_rpc = 19948
basepath = "/dotidx/kusama-acurast-node-archive"
chainreader_ip = "192.168.1.36"
chainreader_port = 21000
sidecar_ip = "192.168.1.36"
sidecar_port = 21000 # will use +1 +2 etc for each sidecar instance
sidecar_count = 5
prometheus_port = 19617
sidecar_prometheus_port = 21050

[filesystem]
zfs = true

[monitoring]
user = "prometheus"
prometheus_ip = "192.168.1.32"
prometheus_port = 9100
